// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa19FyldC63Z90tvFp95omK6_OhxDDm-Q',
    appId: '1:114322835741:web:6a1b99bd04aca854a639f4',
    messagingSenderId: '114322835741',
    projectId: 'famstory-1e19a',
    authDomain: 'famstory-1e19a.firebaseapp.com',
    storageBucket: 'famstory-1e19a.appspot.com',
    measurementId: 'G-VPMR54RBYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcC2KvrcwUkrtHdd6nAwODFLF5YfKhb-s',
    appId: '1:114322835741:android:f660d3c7e24e56eda639f4',
    messagingSenderId: '114322835741',
    projectId: 'famstory-1e19a',
    storageBucket: 'famstory-1e19a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4Vpxyf9RkR60-ld-Ap32NTDvqL256Fgk',
    appId: '1:114322835741:ios:b6dc078d9029da11a639f4',
    messagingSenderId: '114322835741',
    projectId: 'famstory-1e19a',
    storageBucket: 'famstory-1e19a.appspot.com',
    iosBundleId: 'com.example.famStoryFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4Vpxyf9RkR60-ld-Ap32NTDvqL256Fgk',
    appId: '1:114322835741:ios:cf5e5f09723562f3a639f4',
    messagingSenderId: '114322835741',
    projectId: 'famstory-1e19a',
    storageBucket: 'famstory-1e19a.appspot.com',
    iosBundleId: 'com.example.famStoryFrontend.RunnerTests',
  );
}
